before_build:
  - nuget restore


notifications:
  - provider: Email
    to:
      - muhammadmuzzammil.cs@gmail.com
      - nabeelkomer@gmail.com

platform:
  - x86
  - Any CPU

configuration:
  - Debug
  - Release