version: '{build}'
branches:
  only:
  - master
image:
- Visual Studio 2017 Preview
- Visual Studio 2017
init:
- cmd: >-
    "C:\Program Files\Git\mingw64\bin\curl" -O https://download.microsoft.com/download/9/0/1/901B684B-659E-4CBD-BEC8-B3F06967C2E7/NDP471-DevPack-ENU.exe


    NDP471-DevPack-ENU.exe /q /norestart


    exit /B 0
before_build:
- cmd: >-
    "C:\Program Files\Git\mingw64\bin\curl" -O https://download.microsoft.com/download/9/0/1/901B684B-659E-4CBD-BEC8-B3F06967C2E7/NDP471-DevPack-ENU.exe


    NDP471-DevPack-ENU.exe /q /norestart


    exit /B 0
build:
  verbosity: minimal
notifications:
- provider: Email
  to:
  - swsh@muzzammil.xyz
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
