before_build:
  - nuget restore


notifications:
  - provider: Email
    to:
      - muhammadmuzzammil.cs@gmail.com

platform:
  - Any CPU

image: Visual Studio 2017

configuration:
  - Debug
  - Release