version: '{build}'
image: Visual Studio 2017
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
notifications:
- provider: Email
  to:
  - swsh@muzzammil.xyz
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true